// <auto-generated />
namespace Demo1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_TableName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_TableName));
        
        string IMigrationMetadata.Id
        {
            get { return "201708310646218_Change_TableName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
